--NOMEFILE
--Author :
--Date :
--Application:
--Notes :
--
WHENEVER OSERROR EXIT SQL.OSCODE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL ##SPOOL_NAME##.log

SET DEFINE OFF
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF TIMING ON ECHO ON FEEDBACK ON

CREATE OR REPLACE PACKAGE BODY ##OWNER##.##PACKAGE_NAME##
AS
    -- $Id 
    nome_package            CONSTANT VARCHAR2 (50) := '##PACKAGE_NAME##';
    ex_generic_error        EXCEPTION;
    ex_validation_error     EXCEPTION;

    

END ##PACKAGE_NAME##;
/
COMMIT;

SPOOL OFF
EXIT
