--NOMEFILE
--Author :
--Date :
--Application:
--Notes :
--

WHENEVER OSERROR EXIT SQL.OSCODE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL ##SPOOL_NAME##.log

SET DEFINE OFF
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF TIMING ON ECHO ON FEEDBACK ON

CREATE OR REPLACE PACKAGE ##OWNER##.##PACKAGE_NAME##
AS
    -- $Id

                                             

END ##PACKAGE_NAME##;
/
GRANT EXECUTE ON ##OWNER##.##PACKAGE_NAME## TO ##OTHER_SCHEMAS## WITH GRANT OPTION;

COMMIT;

SPOOL OFF
EXIT
